GET http://localhost:3000/api/users/?role=Employee

###
GET http://localhost:3000/orders/
###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Viktor",
    "email": "Viktor@gmail.com",
    "password": "123"
}

###

POST http://localhost:3000/auth/login
Content-Type:application/json

{
    "email": "Viktor@gmail.com",
    "password": "123"
}

###
POST http://localhost:3000/orders/
Content-type: application/json

{
    "sender_id": "69356c8772ae175f0fa88e5a",
    "receiver_id": "6938c32f2f848eb455315777",
    "adress": "asd",
    "weight": "1000"
}

###
PUT http://localhost:3000/users/68fa57eaa1a3340fa0602112
Content-type: application/json

{
    "role":"client"
}


###
POST http://localhost:3000/auth/register-company
Content-Type: application/json

{
    "name": "Viktor",
    "email": "Viktor@gmail.com",
    "password": "123"
}