GET http://localhost:3000/api/users/?role=Employee

###
GET http://localhost:3000/orders/
###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Viktor",
    "email": "Viktor@gmail.com",
    "password": "123"
}

###

POST http://localhost:3000/auth/login
Content-Type:application/json

{
    "email": "Viktor@gmail.com",
    "password": "123"
}

###
POST http://localhost:3000/orders/
Content-type: application/json

{
    "sender_id": "68fa57eaa1a3340fa0602112",
    "receiver_id": "68fa58ff1136ad9d114c4cbc",
    "adress": "nbu",
    "weight": "500"
}

###
PUT http://localhost:3000/users/68fa57eaa1a3340fa0602112
Content-type: application/json

{
    "role":"user"
}


###
POST http://localhost:3000/auth/register-company
Content-Type: application/json

{
    "name": "Viktor",
    "email": "Viktor@gmail.com",
    "password": "123"
}